parameters:
#    j_somerstone_feikki_tupas.example.class: JSomerstone\Feikki\TupasBundle\Example

services:
#    j_somerstone_feikki_tupas.example:
#        class: %j_somerstone_feikki_tupas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
